export const GET_ALL_TITLE_EXAM = "GET_ALL_TITLE_EXAM";
export const GET_EXAM_BY_ID = "GET_EXAM_BY_ID";
export const DELETE_Exam = "DELETE_Exam";
export const UPDATE_EXAM = "UPDATE_EXAM";
export const GET_LIST_USER_RESULT_BY_EXAM_ID = "GET_LIST_USER_RESULT_BY_EXAM_ID";
export const GET_LIST_EXAM_RESULT_BY_USER_ID = "GET_LIST_EXAM_RESULT_BY_USER_ID";